services:
  # Backend API service
  - type: web
    name: ecommerce-api
    env: node
    region: ohio
    plan: free
    buildCommand: cd backend && npm install --legacy-peer-deps
    startCommand: cd backend && npm start
    envVars:
      - key: DB_URL
        value: mongodb+srv://admin:r2327@e-commerce.jdumw.mongodb.net/E-commerce?retryWrites=true&w=majority&appName=E-commerce
      - key: JWT_SECRET_KEY
        value: "r2327"
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: doaryemo6
      - key: CLOUDINARY_API_KEY
        value: 416564381269464
      - key: CLOUDINARY_API_SECRET
        value: PROKUR4-8OnmqbpeUoZIdp8U5OM
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

  # Frontend static site
  - type: web
    name: ecommerce-frontend
    env: static
    region: ohio
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        value: 'http://localhost:3000'
      - key: NODE_ENV
        value: production